[package]
name = "splot"
version = "0.1.0"
authors = ["Felix Zwettler <f.zwettler@posteo.de>"]
edition = "2021"
rust-version = "1.65"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
demo = []

[dependencies]
anyhow = "1"
log = "0.4"
egui = "0.22"
egui_extras = {version = "0.22", features = ["svg"] }
eframe = { version = "0.22", features = ["default_fonts", "wgpu", "persistence"] }
serde = { version = "1", features = ["derive"] } # You only need this if you want app persistence
instant = { version = "0.1", features=["wasm-bindgen"] }
async-trait = "0.1"
futures = "0.3"
once_cell = "1"

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pretty_env_logger = "0.4"
serialport = "4.2"
poll-promise = { git = "https://github.com/EmbarkStudios/poll-promise", rev = "8c4d0d6e4d693cf54e9306950cb2f6d271c77080", features = ["smol"] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "0.2"
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
poll-promise = { git = "https://github.com/EmbarkStudios/poll-promise", rev = "8c4d0d6e4d693cf54e9306950cb2f6d271c77080", features = ["web"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.61"
features = [
    "Window",
    "Navigator",
    "Serial",
    "SerialPort",
    "SerialPortInfo",
    "SerialPortRequestOptions",
    "SerialOptions",
    "ReadableStream",
    "ReadableStreamDefaultReader",
    "ParityType",
    "FlowControlType",
]

[build-dependencies]
anyhow = "1"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]
